name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run:  sudo apt-get update
    - name: Install dependencies
      run: |
        sudo apt-get install -y hunspell-en-gb enchant-2 shellcheck
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pylint --version
    - name: Check Types
      run:  make check-types
    - name: Run Linters
      run:  make lint
    - name: Run Unit Tests
      run:  make test
    - name: Run Unit Tests Coverage
      run:  make coverage
    - name: Check Formatting
      run:  make check-formatting
