name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run:  sudo apt-get update
    - name: Install dependencies
      run: |
        sudo apt-get install -y hunspell-en-gb enchant-2
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylint run-dosbox install-gog-game *.py tests/*.py scripts/*.py
